package ex44;
/*
 *  UCF COP3330 Summer 2021 Assignment 3 Solution
 *  Copyright 2021 Ryan Doherty
 */
// Object needed to store the product array generated by gson
public class Products {
    private Product[] products;

    public Products(Product[] productArray) {
        this.products = productArray;
    }

    public Product[] getProducts() {
        return products;
    }

    public void setProducts(Product[] products) {
        this.products = products;
    }
}
